Deadband logging
Wolkabout/WolkGatewayModule-Modbus pull request #48
Opened 2021-01-05 14:40 UTC by djesic

2021-01-11 07:35 UTC, milanzlicic requested changes
Where do we actually compare values with deadband?

2021-01-11 07:35 UTC, milanzlicic commented on src/model/ModuleMapping.h
> +    float m_deadbandValue = 0.0;
Use double since mixing floats and doubles yields weird bugs

2021-01-11 10:33 UTC, djesic commented
> Where do we actually compare values with deadband?

https://github.com/Wolkabout/MoreModbus/blob/callback_changes/src/RegisterMapping.cpp

2021-01-13 09:16 UTC, milanzlicic approved these changes

2021-01-19 14:45 UTC, milanzlicic approved these changes

2021-01-19 14:54 UTC, merged